### PR TITLE
DF Update

### PR DESCRIPTION
**Pull request by Harshmage**
Added herbs, ore, and lockboxes from Dragonflight 10.0.0.

### CODE REVIEW

**Comment by Xruptor** [comment]
Nice neat!  Thanks for the contribution.  😄 

This addon still works though?  I was told it was broken with Dragonflight and generated errors and what not.  That's why I had discontinued it a few days ago.  I'll double check though if it is working.  Hmm it may just need a few slight fixes but I thought that Blizzard moved all the prospecting/milling stuff to the tradeskill window in Dragonflight.

**Comment by Harshmage** [comment]
I have absolutely NO idea!  😆

If they did move milling and prospecting to the tradeskill window, that would essentially kill most of this addon for Retail.  Lockpicking for Rogues may still work, I'll check it out tonight.

**Comment by Xruptor** [comment]
> I have absolutely NO idea! 😆
> 
> If they did move milling and prospecting to the tradeskill window, that would essentially kill most of this addon for Retail. Lockpicking for Rogues may still work, I'll check it out tonight.

Yeah they moved it to the tradeskill window.  It's not even considered a spell anymore for milling or prospecting.  I would have to force the tradeskill window to open use the recipe then close it really quickly.  Not sure if that's worth it really since you can do mass prospecting and milling now in it.

Either way please test it for me :D  I would appreciate it!

**Comment by Xruptor** [comment]
I haven't heard back in 4 days so I'm going to merge this for the future potentially, but I'll keep the addon discontinued for the time being.

**Comment by Harshmage** [comment]
I had written this comment, but apparently forgot to post it.  Sorry!

Well, I got good news and bad news.  The good news is you don't have to update for Dragonflight!  The bad news is that lockboxes are out of the mix as well.

**Comment by Xruptor** [comment]
> I had written this comment, but apparently forgot to post it. Sorry!
> 
> Well, I got good news and bad news. The good news is you don't have to update for Dragonflight! The bad news is that lockboxes are out of the mix as well.

Well that's a bummer! Yeah I think I'll just keep the addon as discontinued then.  Worse case scenario there is an alternative called Molinari which seems to be up to date.  Thank you so much for getting back to me! 😄

**Pull request merged**
